# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f46ae493dcba788c8cfeb7d2e7060337af0bd4b98fc48baff6cd0386fb1eecf5feb70d21a524b31e748694f38fc899fb56b84ebf9f7961a4734ba61a045c19a

test:
  secret_key_base: 20f7e1b0bfb1e168de241b5188fc3d3a3582a1db3cf3e2b8275d9f157fdfccc6406d568c4c75b044b4a83d89b5c76444737881567805288dffed126aa4f9cb25

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
